### PR TITLE
Fix Xcode 10 warnings related to NS_NOESCAPE

### PR DESCRIPTION
**Pull request by jacobjennings**

### CODE REVIEW

**Comment by shoumikhin** [comment]
Hi Jacob, thank you for the fix!
Do you mind change NSObject+FBLFunctional.m accordingly?
There're should be warnings in that file as well, I guess?
Some warnings logs would be helpful.
Thanks!

**Comment by jacobjennings** [comment]
NSObject+FBLFunctional doesn't have any warnings. Here's the warnings I get:

```
Showing All Messages

Prepare build
note: Using new build systemnote: Planning buildnote: Using build description from memory


Build target FBLFunctional of project FBLFunctional with configuration Debug

CompileC /Users/jacobjennings/Library/Developer/Xcode/DerivedData/FBLFunctional-awuvzymwthwxyhcualiuoavcesez/Build/Intermediates.noindex/FBLFunctional.build/Debug-iphonesimulator/FBLFunctional.build/Objects-normal/x86_64/NSDictionary+FBLFunctional.o /Users/jacobjennings/functional-objc/Sources/FBLFunctional/NSDictionary+FBLFunctional.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target: FBLFunctional)
    cd /Users/jacobjennings/functional-objc
    export LANG=en_US.US-ASCII
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fobjc-arc -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-implicit-atomic-properties -Wno-objc-interface-ivars -Wno-arc-repeated-use-of-weak -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -DOBJC_OLD_DISPATCH_PROTOTYPES=1 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-semicolon-before-method-body -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/jacobjennings/Library/Developer/Xcode/DerivedData/FBLFunctional-awuvzymwthwxyhcualiuoavcesez/Index/DataStore -I/Users/jacobjennings/Library/Developer/Xcode/DerivedData/FBLFunctional-awuvzymwthwxyhcualiuoavcesez/Build/Products/Debug-iphonesimulator/include -I/Users/jacobjennings/functional-objc/Sources/FBLFunctional/include -I/Users/jacobjennings/Library/Developer/Xcode/DerivedData/FBLFunctional-awuvzymwthwxyhcualiuoavcesez/Build/Intermediates.noindex/FBLFunctional.build/Debug-iphonesimulator/FBLFunctional.build/DerivedSources/x86_64 -I/Users/jacobjennings/Library/Developer/Xcode/DerivedData/FBLFunctional-awuvzymwthwxyhcualiuoavcesez/Build/Intermediates.noindex/FBLFunctional.build/Debug-iphonesimulator/FBLFunctional.build/DerivedSources -F/Users/jacobjennings/Library/Developer/Xcode/DerivedData/FBLFunctional-awuvzymwthwxyhcualiuoavcesez/Build/Products/Debug-iphonesimulator -F/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks -MMD -MT dependencies -MF /Users/jacobjennings/Library/Developer/Xcode/DerivedData/FBLFunctional-awuvzymwthwxyhcualiuoavcesez/Build/Intermediates.noindex/FBLFunctional.build/Debug-iphonesimulator/FBLFunctional.build/Objects-normal/x86_64/NSDictionary+FBLFunctional.d --serialize-diagnostics /Users/jacobjennings/Library/Developer/Xcode/DerivedData/FBLFunctional-awuvzymwthwxyhcualiuoavcesez/Build/Intermediates.noindex/FBLFunctional.build/Debug-iphonesimulator/FBLFunctional.build/Objects-normal/x86_64/NSDictionary+FBLFunctional.dia -c /Users/jacobjennings/functional-objc/Sources/FBLFunctional/NSDictionary+FBLFunctional.m -o /Users/jacobjennings/Library/Developer/Xcode/DerivedData/FBLFunctional-awuvzymwthwxyhcualiuoavcesez/Build/Intermediates.noindex/FBLFunctional.build/Debug-iphonesimulator/FBLFunctional.build/Objects-normal/x86_64/NSDictionary+FBLFunctional.o

/Users/jacobjennings/functional-objc/Sources/FBLFunctional/NSDictionary+FBLFunctional.m:89:46: warning: parameter of overriding method should be annotated with __attribute__((noescape)) [-Wmissing-noescape]
- (instancetype)fbl_filter:(BOOL (^)(id, id))predicate {
                                             ^
In file included from /Users/jacobjennings/functional-objc/Sources/FBLFunctional/NSDictionary+FBLFunctional.m:17:
/Users/jacobjennings/functional-objc/Sources/FBLFunctional/include/NSDictionary+FBLFunctional.h:33:79: note: parameter of overridden method is annotated with __attribute__((noescape))
- (instancetype)fbl_filter:(NS_NOESCAPE FBLFunctionalDictionaryPredicateBlock)predicate
                                                                              ^
/Users/jacobjennings/functional-objc/Sources/FBLFunctional/NSDictionary+FBLFunctional.m:95:44: warning: parameter of overriding method should be annotated with __attribute__((noescape)) [-Wmissing-noescape]
- (nullable id)fbl_first:(BOOL (^)(id, id))predicate {
                                           ^
In file included from /Users/jacobjennings/functional-objc/Sources/FBLFunctional/NSDictionary+FBLFunctional.m:17:
/Users/jacobjennings/functional-objc/Sources/FBLFunctional/include/NSDictionary+FBLFunctional.h:39:82: note: parameter of overridden method is annotated with __attribute__((noescape))
- (nullable KeyType)fbl_first:(NS_NOESCAPE FBLFunctionalDictionaryPredicateBlock)predicate
                                                                                 ^
/Users/jacobjennings/functional-objc/Sources/FBLFunctional/NSDictionary+FBLFunctional.m:101:42: warning: parameter of overriding method should be annotated with __attribute__((noescape)) [-Wmissing-noescape]
- (NSArray *)fbl_flatMap:(id (^)(id, id))mapper {
                                         ^
In file included from /Users/jacobjennings/functional-objc/Sources/FBLFunctional/NSDictionary+FBLFunctional.m:17:
/Users/jacobjennings/functional-objc/Sources/FBLFunctional/include/NSDictionary+FBLFunctional.h:46:74: note: parameter of overridden method is annotated with __attribute__((noescape))
- (NSArray *)fbl_flatMap:(NS_NOESCAPE FBLFunctionalDictionaryMapperBlock)mapper
                                                                         ^
/Users/jacobjennings/functional-objc/Sources/FBLFunctional/NSDictionary+FBLFunctional.m:107:39: warning: parameter of overriding method should be annotated with __attribute__((noescape)) [-Wmissing-noescape]
- (void)fbl_forEach:(void (^)(id, id))block {
                                      ^
In file included from /Users/jacobjennings/functional-objc/Sources/FBLFunctional/NSDictionary+FBLFunctional.m:17:
/Users/jacobjennings/functional-objc/Sources/FBLFunctional/include/NSDictionary+FBLFunctional.h:52:73: note: parameter of overridden method is annotated with __attribute__((noescape))
- (void)fbl_forEach:(NS_NOESCAPE FBLFunctionalDictionaryEnumeratorBlock)block
                                                                        ^
/Users/jacobjennings/functional-objc/Sources/FBLFunctional/NSDictionary+FBLFunctional.m:113:38: warning: parameter of overriding method should be annotated with __attribute__((noescape)) [-Wmissing-noescape]
- (NSArray *)fbl_map:(id (^)(id, id))mapper {
                                     ^
In file included from /Users/jacobjennings/functional-objc/Sources/FBLFunctional/NSDictionary+FBLFunctional.m:17:
/Users/jacobjennings/functional-objc/Sources/FBLFunctional/include/NSDictionary+FBLFunctional.h:59:70: note: parameter of overridden method is annotated with __attribute__((noescape))
- (NSArray *)fbl_map:(NS_NOESCAPE FBLFunctionalDictionaryMapperBlock)mapper
                                                                     ^
/Users/jacobjennings/functional-objc/Sources/FBLFunctional/NSDictionary+FBLFunctional.m:119:45: warning: parameter of overriding method should be annotated with __attribute__((noescape)) [-Wmissing-noescape]
- (NSDictionary *)fbl_mapValues:(id (^)(id))mapper {
                                            ^
In file included from /Users/jacobjennings/functional-objc/Sources/FBLFunctional/NSDictionary+FBLFunctional.m:17:
/Users/jacobjennings/functional-objc/Sources/FBLFunctional/include/NSDictionary+FBLFunctional.h:67:58: note: parameter of overridden method is annotated with __attribute__((noescape))
    (NS_NOESCAPE FBLFunctionalDictionaryValueMapperBlock)mapper NS_SWIFT_UNAVAILABLE("");
                                                         ^
/Users/jacobjennings/functional-objc/Sources/FBLFunctional/NSDictionary+FBLFunctional.m:125:81: warning: parameter of overriding method should be annotated with __attribute__((noescape)) [-Wmissing-noescape]
- (nullable id)fbl_reduce:(nullable id)initialValue combine:(id (^)(id, id, id))reducer {
                                                                                ^
In file included from /Users/jacobjennings/functional-objc/Sources/FBLFunctional/NSDictionary+FBLFunctional.m:17:
/Users/jacobjennings/functional-objc/Sources/FBLFunctional/include/NSDictionary+FBLFunctional.h:73:76: note: parameter of overridden method is annotated with __attribute__((noescape))
                  combine:(NS_NOESCAPE FBLFunctionalDictionaryReducerBlock)reducer
                                                                           ^
7 warnings generated.

Ld /Users/jacobjennings/Library/Developer/Xcode/DerivedData/FBLFunctional-awuvzymwthwxyhcualiuoavcesez/Build/Products/Debug-iphonesimulator/FBLFunctional.framework/FBLFunctional normal x86_64 (in target: FBLFunctional)
    cd /Users/jacobjennings/functional-objc
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -dynamiclib -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk -L/Users/jacobjennings/Library/Developer/Xcode/DerivedData/FBLFunctional-awuvzymwthwxyhcualiuoavcesez/Build/Products/Debug-iphonesimulator -F/Users/jacobjennings/Library/Developer/Xcode/DerivedData/FBLFunctional-awuvzymwthwxyhcualiuoavcesez/Build/Products/Debug-iphonesimulator -F/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks -filelist /Users/jacobjennings/Library/Developer/Xcode/DerivedData/FBLFunctional-awuvzymwthwxyhcualiuoavcesez/Build/Intermediates.noindex/FBLFunctional.build/Debug-iphonesimulator/FBLFunctional.build/Objects-normal/x86_64/FBLFunctional.LinkFileList -install_name @rpath/FBLFunctional.framework/FBLFunctional -mios-simulator-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/jacobjennings/Library/Developer/Xcode/DerivedData/FBLFunctional-awuvzymwthwxyhcualiuoavcesez/Build/Intermediates.noindex/FBLFunctional.build/Debug-iphonesimulator/FBLFunctional.build/Objects-normal/x86_64/FBLFunctional_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -Xlinker -dependency_info -Xlinker /Users/jacobjennings/Library/Developer/Xcode/DerivedData/FBLFunctional-awuvzymwthwxyhcualiuoavcesez/Build/Intermediates.noindex/FBLFunctional.build/Debug-iphonesimulator/FBLFunctional.build/Objects-normal/x86_64/FBLFunctional_dependency_info.dat -o /Users/jacobjennings/Library/Developer/Xcode/DerivedData/FBLFunctional-awuvzymwthwxyhcualiuoavcesez/Build/Products/Debug-iphonesimulator/FBLFunctional.framework/FBLFunctional

CodeSign /Users/jacobjennings/Library/Developer/Xcode/DerivedData/FBLFunctional-awuvzymwthwxyhcualiuoavcesez/Build/Products/Debug-iphonesimulator/FBLFunctional.framework (in target: FBLFunctional)
    cd /Users/jacobjennings/functional-objc
    export CODESIGN_ALLOCATE=/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --timestamp=none /Users/jacobjennings/Library/Developer/Xcode/DerivedData/FBLFunctional-awuvzymwthwxyhcualiuoavcesez/Build/Products/Debug-iphonesimulator/FBLFunctional.framework
```

**Comment by jacobjennings** [comment]
I think we don't see warnings on the NSObject category because we're doing something unusual by implementing the category interfaces on NSDictionary, NSArray, etc using a shared NSObject implementation

**Comment by jacobjennings** [comment]
test failure: no such target '@bazel_tools//tools/objc:ios_runner.sh.mac_template'

```
ERROR: /Users/travis/build/google/functional-objc/BUILD:31:1: every rule of type _ios_test_bundle implicitly depends upon the target '@bazel_tools//tools/objc:ios_runner.sh.mac_template', but this target could not be found because of: no such target '@bazel_tools//tools/objc:ios_runner.sh.mac_template': target 'ios_runner.sh.mac_template' not declared in package 'tools/objc' defined by /private/var/tmp/_bazel_travis/420527183e133c823bb3988a1b2621af/external/bazel_tools/tools/objc/BUILD
```

**Comment by jacobjennings** [comment]
Tests passing 🎉

**Pull request merged**
